<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1 (Recalling terms)

|Term|Brief description|
|:---|:--:|
|Subsetting|It means to select.|
|Indexing|It means to select a single element.|
|Slicing|It means to select a range of elements.|
|Masking||

# Exercise 2 (Subsetting 'odd' letters)

In [2]:
import numpy as np

In [9]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
np_array_2d[0:10,0]

# how to get rid of back part

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [19]:
np_array = np.array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')
np_array.astype(int)

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [20]:
np_array = np.array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])
np_array%2

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [7]:
np_array = np.array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])
my_mask = np_array > 0
my_mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [11]:
np_array[my_mask]

array([1, 1, 1, 1, 1])

# Exercise 3 (Using NumPy masking)