<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1 (Recalling terms)

|Term|Brief description|
|:---|:--:|
|Subsetting|It means to select an element or a range of elements from a list or an array.|
|Indexing|It means to select a single element from a list or an array.|
|Slicing|It means to select a range of elements from a list or an array.|
|Masking|*It means to select a subset to be shown from an array.*|

# Exercise 2 (Subsetting 'odd' letters)

In [28]:
import numpy as np

## Subsetting first elements

In [72]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"], [5, "E"], [7, "G"], [6, "F"], [8, "H"], [10, "J"], [9, "I"]])
np_array_2d[0:10,0]

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

## astype(int)

In [9]:
np_array_integers = np.array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')
np_array_integers.astype(int)

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

## Obtaining the remainder

In [10]:
np_array_remainder = np.array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])
np_array_remainder%2

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

## Checking if remainder is 0 or not

In [11]:
np_array_truefalse = np.array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])
my_mask = np_array_truefalse > 0
my_mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

## Final result

In [8]:
np_array_2d[my_mask]

array([['1', 'A'],
       ['3', 'C'],
       ['5', 'E'],
       ['7', 'G'],
       ['9', 'I']], dtype='<U21')

In [74]:
np_array_answer = np.array([['1', 'A'], ['3', 'C'], ['5', 'E'], ['7', 'G'], ['9', 'I']],  dtype='<U21')
np_array_answer[0:5,1]

# Need to +1 to last index

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

# Exercise 3 (Using NumPy masking)

In [57]:
py_list_2d = [[66, 50, 57, -1, -1], [92, -1, 88, -1, -1], [75, -1, -1, 76, -1], [-1, 51, 87, -1, -1], [71, -1, 67, -1, 69]]
np_array_2d = np.array(py_list_2d)
print(np_array_2d)

[[66 50 57 -1 -1]
 [92 -1 88 -1 -1]
 [75 -1 -1 76 -1]
 [-1 51 87 -1 -1]
 [71 -1 67 -1 69]]


## Changing values below 50 to -1

In [58]:
my_mask1 = np_array_2d < 50
np_array_2d[my_mask1] = -1
np_array_2d[my_mask1] 
print(np_array_2d)

[[66 50 57 -1 -1]
 [92 -1 88 -1 -1]
 [75 -1 -1 76 -1]
 [-1 51 87 -1 -1]
 [71 -1 67 -1 69]]


## Changing values above 50 to +1

In [60]:
my_mask2 = np_array_2d > 50
np_array_2d[my_mask2] = 1
np_array_2d[my_mask2] 
print(np_array_2d)

[[ 1 50  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]


## Changing values equal to 50 to 0

In [61]:
my_mask3 = np_array_2d == 50
np_array_2d[my_mask3] = 0
print(np_array_2d)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
