<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

In [2]:
import numpy as np

# Subsetting: Indexing and Slicing

## Lists & Arrays in 1D | Subsetting & Indexing

In [12]:
py_list=["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# can pick x = py_list OR x = np_array

In [14]:
x = py_list

In [16]:
x[2:8:2]

['c3', 'e5', 'g7']

## Arrays only | Subsetting by masking

In [6]:
np_array = np.array([1,2,43,4,5,6,7,8,9,10])
my_mask = np_array > 3
my_mask

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [8]:
np_array[my_mask]

array([43,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np_array = np.array([1,2,3,4,5,6,7,8,9,10])
my_mask = (np_array > 3) & (np_array < 8)
np_array[my_mask]

array([4, 5, 6, 7])

## Lists & Arrays in 2D | Indexing & Slicing

In [ ]:
py_list_2d = [[1, "a", [2, "B", [3, "C"], [4, "D"], [5, "E"], [6, "F"], [7, "G"], [""]

# 2d means only need 2 numbers to access
# 3d means need 3 numbers to access, doesn't meant there's 3 numbers in each []

## 1.4 Growing lists

# Some loose ends

## 1.5 Tuples

## 1.6 Be VERY careful when copying

## Footnotes